# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([
    [1,2,3],
    [4,5,6]
])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])
a3.ndim

3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [7]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1)

(1, dtype('int64'), 3, numpy.ndarray)

In [8]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int64'), 6, numpy.ndarray)

In [9]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3)

(3, dtype('int64'), 18, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a3_df = pd.DataFrame(a3.reshape(6,3))
a3_df

0  1  2
0  1  2  3
1  4  5  6
2  1  2  3
3  4  5  6
4  1  2  3
5  4  5  6

In [16]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [19]:
# Create an array within a range of 0 and 100 with step 3
arange = np.arange(0, 100, step=3)
arange

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0,10, size=(7,2))
random_array

array([[5, 6],
       [7, 3],
       [6, 1],
       [3, 8],
       [5, 5],
       [0, 9],
       [8, 7]])

In [25]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_arr_float = np.random.rand(3,5)
random_arr_float

array([[0.595019  , 0.71931139, 0.46476926, 0.74437711, 0.51842392],
       [0.12271037, 0.60838675, 0.8116389 , 0.68328006, 0.64599108],
       [0.0805973 , 0.87454166, 0.32424501, 0.73106803, 0.3707164 ]])

In [27]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr_2 = np.random.rand(4,6)
random_arr_2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr1 = np.random.randint(1,10,size=(3,7))
# Find the unique numbers in the array you just created
np.unique(arr1)

array([2, 3, 4, 5, 7, 8, 9])

In [35]:
arr1

array([[3, 7, 4, 9, 3, 5, 3],
       [7, 5, 9, 7, 2, 4, 9],
       [2, 9, 5, 2, 4, 7, 8]])

In [32]:
# Find the 0'th index of the latest array you created
arr1[0]

array([3, 7, 4, 9, 3, 5, 3])

In [34]:
# Get the first 2 rows of latest array you created
arr1[:2]

array([[3, 7, 4, 9, 3, 5, 3],
       [7, 5, 9, 7, 2, 4, 9]])

In [36]:
# Get the first 2 values of the first 2 rows of the latest array
arr1[:2, :2]

array([[3, 7],
       [7, 5]])

In [40]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_arr_1 = np.random.randint(0, 10, size=(3,5))
random_arr_2 = np.ones((3,5))
random_arr_1, random_arr_2

(array([[9, 8, 6, 8, 7],
        [1, 0, 6, 6, 7],
        [4, 2, 7, 5, 2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [43]:
# Add the two arrays together
combined_arr = random_arr_1 + random_arr_2

In [42]:
# Create another array of ones of shape (5, 3)
random_arr_3 = np.ones((5,3))
random_arr_3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [49]:
# Try add the array of ones and the other most recent array together
combined_arr_0 = random_arr_3.T + combined_arr

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [46]:
# Create another array of ones of shape (3, 5)
random_arr_4 = np.ones((3,5))

In [53]:
# Subtract the new array of ones from the other most recent array
latest_arr_0 = combined_arr_0 - random_arr_4
latest_arr_0

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [55]:
# Multiply the ones array with the latest array
latest_arr_1 = latest_arr_0 * random_arr_4
latest_arr_1

array([[10.,  9.,  7.,  9.,  8.],
       [ 2.,  1.,  7.,  7.,  8.],
       [ 5.,  3.,  8.,  6.,  3.]])

In [56]:
# Take the latest array to the power of 2 using '**'
latest_arr_1**2

array([[100.,  81.,  49.,  81.,  64.],
       [  4.,   1.,  49.,  49.,  64.],
       [ 25.,   9.,  64.,  36.,   9.]])

In [57]:
# Do the same thing with np.square()
np.square(latest_arr_1)

array([[100.,  81.,  49.,  81.,  64.],
       [  4.,   1.,  49.,  49.,  64.],
       [ 25.,   9.,  64.,  36.,   9.]])

In [58]:
# Find the mean of the latest array using np.mean()
np.mean(latest_arr_1)

6.2

In [59]:
# Find the maximum of the latest array using np.max()
np.max(latest_arr_1)

10.0

In [60]:
# Find the minimum of the latest array using np.min()
np.min(latest_arr_1)

1.0

In [61]:
# Find the standard deviation of the latest array
np.std(latest_arr_1)

2.6882460204874605

In [62]:
# Find the variance of the latest array
np.var(latest_arr_1)

7.2266666666666675

In [63]:
# Reshape the latest array to (3, 5, 1)
latest_arr_1.reshape(3,5,1)

array([[[10.],
        [ 9.],
        [ 7.],
        [ 9.],
        [ 8.]],

       [[ 2.],
        [ 1.],
        [ 7.],
        [ 7.],
        [ 8.]],

       [[ 5.],
        [ 3.],
        [ 8.],
        [ 6.],
        [ 3.]]])

In [64]:
# Transpose the latest array
latest_arr_1.T

array([[10.,  2.,  5.],
       [ 9.,  1.,  3.],
       [ 7.,  7.,  8.],
       [ 9.,  7.,  6.],
       [ 8.,  8.,  3.]])

What does the transpose do?

In [66]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_ones_0 = np.random.randint(0, 10, size = (3,3))
array_ones_1 = np.random.randint(0, 10, size = (3,2))
array_ones_0, array_ones_1

(array([[3, 3, 4],
        [6, 6, 3],
        [6, 2, 5]]),
 array([[1, 9],
        [8, 4],
        [5, 3]]))

In [67]:
# Perform a dot product on the two newest arrays you created
np.dot(array_ones_0, array_ones_1)

array([[47, 51],
       [69, 87],
       [47, 77]])

In [68]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_random_0 = np.random.randint(0, 10, size=(4,3))
array_random_1 = np.random.randint(0, 10, size=(4,3))
array_random_0, array_random_1

(array([[9, 6, 8],
        [6, 0, 0],
        [8, 8, 3],
        [8, 2, 6]]),
 array([[5, 7, 8],
        [4, 0, 2],
        [9, 7, 5],
        [7, 8, 3]]))

In [69]:
# Perform a dot product on the two newest arrays you created
np.dot(array_random_0, array_random_1)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [70]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array_random_0, array_random_1.T)

array([[151,  52, 163, 135],
       [ 30,  24,  54,  42],
       [120,  38, 143, 129],
       [102,  44, 116,  90]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [71]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
rand_0 = np.random.randint ( 0, 10, size = (3,2,3))
rand_1 = np.random.randint ( 0, 10, size = (3,2,3))
rand_0, rand_1

(array([[[0, 0, 9],
         [3, 6, 1]],
 
        [[2, 0, 4],
         [0, 7, 0]],
 
        [[0, 1, 1],
         [5, 6, 4]]]),
 array([[[0, 0, 2],
         [1, 4, 9]],
 
        [[5, 6, 3],
         [6, 7, 0]],
 
        [[5, 7, 4],
         [3, 1, 5]]]))

In [73]:
# Compare the two arrays with '>'
rand_0 > rand_1

array([[[ True,  True,  True],
        [ True,  True, False]],

       [[False, False,  True],
        [False,  True,  True]],

       [[False, False, False],
        [ True,  True, False]]])

What happens when you compare the arrays with `>`?

In [74]:
# Compare the two arrays with '>='
rand_0 >= rand_1

array([[[ True,  True,  True],
        [ True,  True, False]],

       [[False, False,  True],
        [False,  True,  True]],

       [[False, False, False],
        [ True,  True, False]]])

In [80]:
# Find which elements of the first array are greater than 7
rand_0[rand_0 > 6]
rand_0

array([[[0, 0, 9],
        [3, 6, 1]],

       [[2, 0, 4],
        [0, 7, 0]],

       [[0, 1, 1],
        [5, 6, 4]]])

In [81]:
# Which parts of each array are equal? (try using '==')
rand_0 == rand_1

array([[[ True,  True, False],
        [False, False, False]],

       [[False, False, False],
        [False,  True,  True]],

       [[False, False, False],
        [False, False, False]]])

In [85]:
# Sort one of the arrays you just created in ascending order
rand_0, np.sort(rand_0)

(array([[[0, 0, 9],
         [3, 6, 1]],
 
        [[2, 0, 4],
         [0, 7, 0]],
 
        [[0, 1, 1],
         [5, 6, 4]]]),
 array([[[0, 0, 9],
         [1, 3, 6]],
 
        [[0, 2, 4],
         [0, 0, 7]],
 
        [[0, 1, 1],
         [4, 5, 6]]]))

In [86]:
# Sort the indexes of one of the arrays you just created
np.argsort(rand_0)

array([[[0, 1, 2],
        [2, 0, 1]],

       [[1, 0, 2],
        [0, 2, 1]],

       [[0, 1, 2],
        [2, 0, 1]]])

In [87]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(rand_0)

2

In [88]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(rand_0)

0

In [89]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
rand_0, np.argmax(rand_0, axis=1)

(array([[[0, 0, 9],
         [3, 6, 1]],
 
        [[2, 0, 4],
         [0, 7, 0]],
 
        [[0, 1, 1],
         [5, 6, 4]]]),
 array([[1, 1, 0],
        [0, 1, 0],
        [1, 1, 1]]))

In [90]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
rand_0, np.argmin(rand_0, axis=0)

(array([[[0, 0, 9],
         [3, 6, 1]],
 
        [[2, 0, 4],
         [0, 7, 0]],
 
        [[0, 1, 1],
         [5, 6, 4]]]),
 array([[0, 0, 2],
        [1, 0, 1]]))

In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.